export const REGISTER = "REGISTER"
export const LOGIN = "LOGIN"
export const FORGOT_PASSWORD = "FORGOT_PASSWORD"
export const VERIFY_OTP = "VERIFY_OTP"
export const CREATE_PASSWORD = "CREATE_PASSWORD"
export const RESET_PASSWORD = "RESET_PASSWORD"
export const UPDATE_USER = "UPDATE_USER"
export const DASHBOARD = "DASHBOARD"
export const DASHBOARD_RESPONSE = "DASHBOARD_RESPONSE"
export const SESSIONS = "SESSIONS"
export const SESSIONS_RESPONSE = "SESSIONS_RESPONSE"
export const SESSIONSDETAILS = "SESSIONSDETAILS"
export const SESSIONSDETAILS_RESPONSE = "SESSIONSDETAILS_RESPONSE"
export const NOTIFICATION = "NOTIFICATION"
export const NOTIFICATION_RESPONSE = "NOTIFICATION_RESPONSE"

export const UPDATE_CACHE = "UPDATE_CACHE"
export const UPDATE_IMAGES = "UPDATE_IMAGES"
export const IS_USERS = "IS_USERS"
export const CHECK_LOGIN = "CHECK_LOGIN"
export const LOADINNG = "LOADINNG"
export const SHIPMENTINFO = "SHIPMENTINFO"




export const FETCH_STORE_LIST = "FETCH_STORE_LIST"
export const FETCH_STORE_LIST_SUCCESS = "FETCH_STORE_LIST_SUCCESS"
export const FETCH_STORE_LIST_FAILURE = "FETCH_STORE_LIST_FAILURE"

export const FETCH_STORE_DETAILS= "FETCH_STORE_DETAILS"
export const FETCH_STORE_DETAILS_SUCCESS = "FETCH_STORE_DETAILS_SUCCESS"
export const FETCH_STORE_DETAILS_FAILURE = "FETCH_STORE_DETAILS_FAILURE"


export const FETCH_ADDRESS_LIST = "FETCH_ADDRESS_LIST"
export const FETCH_ADDRESS_LIST_SUCCESS = "FETCH_ADDRESS_LIST_SUCCESS"
export const FETCH_ADDRESS_LIST_FAILURE = "FETCH_ADDRESS_LIST_FAILURE"

export const ADD_NEW_ADDRESS = "ADD_NEW_ADDRESS"
export const ADD_NEW_ADDRESS_SUCCESS = "ADD_NEW_ADDRESS_SUCCESS"
export const ADD_NEW_ADDRESS_FAILURE = "ADD_NEW_ADDRESS_FAILURE"

export const GET_ORDER = "GET_ORDER"
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS"
export const GET_ORDER_FAILURE = "GET_ORDER_FAILURE"

export const PLAN_LIST = "PLAN_LIST"
export const PLAN_LIST_SUCCESS = "PLAN_LIST_SUCCESS"
export const PLAN_LIST_FAILURE = "PLAN_LIST_FAILURE"

export const PLAN_DETAILS = "PLAN_DETAILS"
export const PLAN_DETAILS_SUCCESS = "PLAN_DETAILS_SUCCESS"
export const PLAN_DETAILS_FAILURE = "PLAN_DETAILS_FAILURE"

export const PROFILE_DETAILS = "PROFILE_DETAILS"
export const PROFILE_DETAILS_SUCCESS = "PROFILE_DETAILS_SUCCESS"
export const PROFILE_DETAILS_FAILURE = "PROFILE_DETAILS_FAILURE"

export const UPDATE_PROFILE_DETAILS = "UPDATE_PROFILE_DETAILS"
export const UPDATE_PROFILE_DETAILS_SUCCESS = "UPDATE_PROFILE_DETAILS_SUCCESS"
export const UPDATE_PROFILE_DETAILS_FAILURE = "UPDATE_PROFILE_DETAILS_FAILURE"

export const NOTIFICATION_LIST = "NOTIFICATION_LIST"
export const NOTIFICATION_LIST_SUCCESS = "NOTIFICATION_LIST_SUCCESS"
export const NOTIFICATION_LIST_FAILURE = "NOTIFICATION_LIST_FAILURE"

export const REMOVE_NOTIFICATION = "REMOVE_NOTIFICATION_LIST"
export const REMOVE_NOTIFICATION_SUCCESS = "REMOVE_NOTIFICATION_SUCCESS"
export const REMOVE_NOTIFICATION_FAILURE = "REMOVE_NOTIFICATION_FAILURE"


export const CHANGE_PASSWORD = "CHANGE_PASSWORD"
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS"
export const CHANGE_PASSWORD_FAILURE = "CHANGE_PASSWORD_FAILURE"




